services:
  - type: web
    name: shipray-logistic
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shiplogsitic.onrender.com
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://shipray-logistic.onrender.com
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
