services:
  - type: web
    name: shipray-logistic
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app .
    startCommand: ./app
    healthCheckPath: /healthz
    envVars:
      - key: API_BASE_URL
        value: https://shipray-logisticbackend.onrender.com
      - key: BACKEND_URL
        value: https://shipray-logisticbackend.onrender.com
      - key: FRONTEND_URL
        value: https://shipray-logistic.onrender.com
